# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06b1c2a4d75b377ca73d9761d9ea5e4969f895a8311b3f7292f773c6179e221601ad406e19ae6cd3b93baa03ee20d55077e0612cbd34c02b2ccda32293c63b0c

test:
  secret_key_base: 2105f262d1bcc71fda23a20ebb224188e3e53a6be36c49080485083a3f9bc8200e09d940182285797ce84ab54d4331df587bb51451b765645095faa7166d1063

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
